### ISSUE TITLE
Discuss idea for feature to be added to library 

### ISSUE THREAD

**Issue by j6626** [cs207group4/cs207-FinalProject#15]

**Comment by kimiamavon** [comment]
There is a Cs/Stats party on Friday MD ground floor at 5. Why don't we meet at 4 or 4:30, before the party starts. And then we can enjoy drinks and snacks once we're done? :)

**Comment by kimiamavon** [comment]
Alternatively, Thursday? Saturday and Sunday I'm very free.

**Comment by kimiamavon** [comment]
@dsondak if we want to be ambitious, could we use scipy to help speed up our code?

**Comment by xuwd11** [comment]
I am okay with Friday afternoon (or weekend), but I am not sure whether I am able to come to Cambridge for the meeting since it takes me one hour to travel forth and back and it would be very inefficient for me to spend one hour on road for a 0.5-hour meeting. In case I couldn't go to Cambridge on Friday, could we schedule a skype meeting, where you guys meet on campus and I join the meeting by skyping or calling one of you?

**Comment by dsondak** [comment]
@kimiamavon, you can use SciPy if you'd like, but I wouldn't call that a feature, per se.  It would amount to a possible code-refactoring.  That's not a small amount of work.  However, a feature would be something that a potential user my like to use in addition to the already-existing capabilities.

**Comment by zeruniverse** [comment]
@dsondak I thought Kimia meant using `scipy.integrate.ode` to solve the system (a new feature) instead of writing a ODE solver from the sketch (which might not be optimized...).

**Comment by j6626** [comment]
I don't think I can do Friday afternoon - I need to go take care of some
visa stuff for a conference...

**Comment by dsondak** [comment]
@zeruniverse, @kimiamavon That is a fantastic idea!  Try to come up with a plan but hold off on implementing it until after the review.

**Comment by kimiamavon** [comment]
Good luck @j6626! I am largely free on Saturday/Sunday with preference for late morning or afternoon. We can skype or facetime @xuwd11 in. My number is 954 494 1614 and work skype name is Harvardcrcs

**Comment by zeruniverse** [comment]
Vote for Sat. Morning @MD(preferred 10AM-)

**Comment by j6626** [comment]
I can do Saturday morning but would have to leave by 11 am. Alternatively I
can do anytime Sunday.

**Comment by xuwd11** [comment]
I do Saturday morning remotely (through skype).

**Comment by zeruniverse** [comment]
How about Sunday @10AM then ?

**Comment by xuwd11** [comment]
I can also do Sunday morning at least remotely and possibly on site.

**Comment by j6626** [comment]
that would be fine with me too.

**Comment by zeruniverse** [comment]
@kimiamavon are you ok with sunday 10AM @ MD?

**Comment by kimiamavon** [comment]
works for me!

**Comment by xuwd11** [comment]
I need to be skyped in since I cannot make it to Cambridge on time.

**Comment by kimiamavon** [comment]
**Ideas**

1. ODE solver
- using scipy.integrate.ode to solve the system (a new feature) instead of writing a ODE solver from the sketch (which might not be optimized...)// species v time// use scipy lib // use a test to see if its going to work.  
- print warning message if negative concentration. ODE at a fixed temp may give neg, will need to tune the parameters? how to handle this???  Ask David for input. 

2. Viz
- Write a visualization library for the output of ODE. // Can use matplotlib or Seaborn // [[what would this look like?  figure [here](https://en.wikipedia.org/wiki/Lotka%E2%80%93Volterra_equations) ]] [c] by time.. requires all [c] to be solved, need to fix temperature. Assume temperature to be constant. 
- should the visualization be able to read xml files and plot things from Milestone 1? or would this only be for ODE solved equations? Milestone one don't have [c] as function of time. It should take the xml files from ex 1 and automatically solve the ODE. [species] v time. Input time, and the species they want to viz--> we generate plot. 

@j6626 @xuwd11 @zeruniverse

**Comment by kimiamavon** [comment]
Dear @dsondak , 

We'd appreciate your thoughts on this. If you have further comments we'll stop by Friday's OH (11:30 AM - 1:00 PM). 

Thank you!
Kimia

**Comment by dsondak** [comment]
Both of these sound great!  We should discuss some of the finer points on Friday.

**Comment by kimiamavon** [comment]
Notes for David

Make options for people- what integrator? 
store solution- xml, hdf5?, txt ascii. 
Viz: maybe more than one plot, maybe chose which species, default behavior, 

make an interface to scipy? 

output file format

Assume temperatures are help constant.

**Comment by kimiamavon** [comment]
Notes from group meeting: 
packaging—> init.py file

Smaller package ex: 
Before test

Write up: Proposed Featured- by Saturday (3 pages); work on it wednesday

Final feature: 
Sci py solver, get nonsense results because eon not trivial to solve well.. chose correct ODE solver. By hand. 

Viz rxns that emphasize whats important. 

Viz what species are reacting with one another and spexial and projects and a chemical network. i.e. any rxn that has h20 in it has a branch to the products/reactants that use H20. Color scale for showing in and out?

**Comment by kimiamavon** [comment]
What visualizations? mat plot lib. but what does network analysis? https://blog.dominodatalab.com/social-network-analysis-with-networkx/

**Comment by kimiamavon** [comment]
DO NOT implement our own time integrator 

Is the expression for calculating progress rates in chemkin are accurate?
