### ISSUE TITLE
Implement ODE solver

### ISSUE THREAD

**Issue by zeruniverse** [cs207group4/cs207-FinalProject#27]

**Comment by xuwd11** [comment]
@zeruniverse @j6626 @kmavon 
Hi all, 

I've implemented and pushed the first version of ChemSolver (with code documentations and tests), which could be used for the implementation of vis features. 
Currently the coverage is low. All tests work on my computer, but somehow test_IO cannot pass on Travis; the error message is "Fatal Python error: Cannot recover from stack overflow", which I haven't figured out the reason yet. I commented the relevant test code in test_ChemSolver.py at the moment.
Feel free to change codes or reimplement methods as needed. Feedbacks and comments are appreciated.

Best,
Weidong

**Comment by zeruniverse** [comment]
@j6626 @kmavon

I made an API for visualization, where you can get a pandas df of all data.

I wrote a jupyter notebook for demo [here](https://github.com/cs207group4/cs207-FinalProject/blob/master/demo_notebook/demo_ODESolver.ipynb).

**Comment by zeruniverse** [comment]
@xuwd11 I fixed stack overflow issue. Coverage raised to 95%

**Comment by j6626** [comment]
about how long does it take to run the demo? I've been having issues, and
I'm not sure whether it's my computer or whether it should just be taking
that long.

**Comment by zeruniverse** [comment]
It took 20 seconds ish on my computer. Make sure you have newest Scipy
(which I guess should be 1.0.0).

**Comment by zeruniverse** [comment]
@j6626 Are you finally able to run it?

**Comment by j6626** [comment]
yes, it seemed I also needed to upgrade NumPy to get it to work on my
computer.

**Comment by j6626** [comment]
have you had any issues with using this on reversible reactions?

**Comment by zeruniverse** [comment]
@j6626 No. For some input it will be very slow. But this is a mathematical problem (does not converge)

**Comment by j6626** [comment]
I've been comparing results from scipy.integrate.solve_ivp and scipy.integrate.ode with the LSODA solver and the results seem somewhat concerning. With ostensibly identical inputs, it looks like scipy.integrate.ode can find a solution when scipy.integrate.solve_ivp fails. I put a couple examples in demo_equilibrium.ipynb. Since this was a single reversible reaction, I also calculated the expected equilibrium concentrations to check that the output of scipy.integrate.ode was reasonable (and it was). @xuwd11 do you have any insights as to what's causing the difference?

**Comment by zeruniverse** [comment]
I think you can set method to be LSODA in solve_ivp (you can add an
optional method Parma in solver input). The default method is RK45. If the
result is still different, I have no idea.

**Comment by j6626** [comment]
The demo notebook I pointed to already uses lsoda for both solvers, so I
would think it should be the same. I think it might be better to change
over to scipy.integrate.ode unless there's a compelling reason to use
solve_ivp.

**Comment by xuwd11** [comment]
Thanks for the suggestion! @j6626 
It seems the output could be very different when we use different algorithms. I also got some wired results when using solve_ivp. I've made the change as you suggested since scipy.integrate.ode seems to be more robust.

**Comment by zeruniverse** [comment]
@j6626 @xuwd11 

I can fix the `nan` problem by using the following (adding the `first_step` param)

print(solve_ivp(cs._ChemSolver__dy_dt, 
          t_span=(0, 6e-5), 
          y0=x_init, 
          t_eval=np.linspace(0,6e-5,20),first_step=3.15789474e-08, method = 'LSODA'))

By using `ode` method, setting `dt` would be very challenging. I don't know if `odeint` function in scipy does a better job.

**Comment by j6626** [comment]
It gets rid of the NaNs but doesn't appear to be converging to the correct
value.

odeint is just a wrapper around ode, but only with the LSODA option.

Since Weidong's already done the rewrite to use ode, I would rather just
stick with that. I'm reluctant to use a scipy feature that was only
introduced a few weeks ago, since it seems like there are some subtleties
that would make our own package less user-friendly.

**Comment by zeruniverse** [comment]
OK. Then we should discuss the default dt. (and maybe make it adaptive)
