### ISSUE TITLE
Combine Viz docs

### ISSUE THREAD

**Issue by kimiamavon** [cs207group4/cs207-FinalProject#33]
Hi @j6626 , 

Shall we combine py documents? or call them different names?

Looking forward to chatting tomorrow!

**Comment by j6626** [comment]
Is the version up on the repo everything you're planning to push before
tomorrow? If so, I can integrate them right now. I'm just working on some
documentation before I push.

**Comment by zeruniverse** [comment]
I thought we've discussed on Wednesday that a ChemSolver object will be passed in to the ChemViz init function as users might not want to save a csv file... But anyway, html_report will not work if I only have access to a csv file. I think Weidong has implemented the SimpleIO which allows user to save the whole ChemSolver object and load a saved ChemSolver object.

I wrote a ChemViz module here which is based on ChemSolver object: https://github.com/cs207group4/cs207-FinalProject/blob/master/pychemkin/ChemViz.py I would appreciate it if we can use this, otherwise in html_report function I have to load a ChemSolver object again...

**Comment by j6626** [comment]
I think you guys might have forgotten to loop Kimia in when you went ahead
with that plan.

**Comment by zeruniverse** [comment]
@j6626 Ooops, I wrote an empty `ChemViz` after our discussion on Wed. in class. I thought we all knew this... to be honest, I didn't pay attention to the details of her implementation before this issue... Sorry for the inconvenience.

**Comment by j6626** [comment]
ok, well I've been integrating my own part into the skeleton ChemViz class
so I think it will be straightforward to combine it with Kimia's work.
